-- AlphaRL-Quant Database Schema
-- PostgreSQL initialization script

-- =============================================================================
-- Market Data Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS market_data (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    open DECIMAL(12, 4),
    high DECIMAL(12, 4),
    low DECIMAL(12, 4),
    close DECIMAL(12, 4) NOT NULL,
    volume BIGINT,
    adj_close DECIMAL(12, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ticker, date)
);

CREATE INDEX idx_ticker_date ON market_data(ticker, date DESC);
CREATE INDEX idx_date ON market_data(date DESC);

COMMENT ON TABLE market_data IS 'Historical OHLCV market data from various sources';

-- =============================================================================
-- Model Checkpoints Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS model_checkpoints (
    id SERIAL PRIMARY KEY,
    model_name VARCHAR(100) NOT NULL,
    checkpoint_path TEXT NOT NULL,
    timestep INTEGER,
    mean_reward DECIMAL(10, 4),
    std_reward DECIMAL(10, 4),
    episode_length DECIMAL(10, 2),
    sharpe_ratio DECIMAL(10, 4),
    max_drawdown DECIMAL(10, 4),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB,
    CONSTRAINT positive_timestep CHECK (timestep >= 0)
);

CREATE INDEX idx_model_timestep ON model_checkpoints(model_name, timestep DESC);
CREATE INDEX idx_mean_reward ON model_checkpoints(mean_reward DESC);

COMMENT ON TABLE model_checkpoints IS 'RL model training checkpoints with performance metrics';

-- =============================================================================
-- Pipeline Runs Table
-- =============================================================================
CREATE TABLE IF NOT EXISTS pipeline_runs (
    id SERIAL PRIMARY KEY,
    run_id UUID DEFAULT gen_random_uuid(),
    status VARCHAR(20) CHECK (status IN ('started', 'running', 'completed', 'failed')),
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    duration_seconds INTEGER GENERATED ALWAYS AS (
        EXTRACT(EPOCH FROM (end_time - start_time))::INTEGER
    ) STORED,
    rows_processed INTEGER,
    features_generated INTEGER,
    error_message TEXT,
    config JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_pipeline_status ON pipeline_runs(status);
CREATE INDEX idx_pipeline_start_time ON pipeline_runs(start_time DESC);

COMMENT ON TABLE pipeline_runs IS 'Audit log of pipeline executions';

-- =============================================================================
-- Feature Store Table (optional, for caching)
-- =============================================================================
CREATE TABLE IF NOT EXISTS feature_cache (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    date TIMESTAMP NOT NULL,
    feature_set_version VARCHAR(20),
    features JSONB NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(ticker, date, feature_set_version)
);

CREATE INDEX idx_feature_ticker_date ON feature_cache(ticker, date DESC);

COMMENT ON TABLE feature_cache IS 'Cached engineered features to avoid recomputation';

-- =============================================================================
-- Trading Signals Table (for backtesting)
-- =============================================================================
CREATE TABLE IF NOT EXISTS trading_signals (
    id SERIAL PRIMARY KEY,
    ticker VARCHAR(10) NOT NULL,
    signal_date TIMESTAMP NOT NULL,
    action VARCHAR(10) CHECK (action IN ('BUY', 'SELL', 'HOLD')),
    price DECIMAL(12, 4),
    shares INTEGER,
    portfolio_value DECIMAL(15, 2),
    model_version VARCHAR(50),
    confidence DECIMAL(5, 4),
    metadata JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_signal_ticker_date ON trading_signals(ticker, signal_date DESC);
CREATE INDEX idx_signal_action ON trading_signals(action);

COMMENT ON TABLE trading_signals IS 'Trading signals generated by RL models for backtesting';

-- =============================================================================
-- Functions and Triggers
-- =============================================================================

-- Update timestamp trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply trigger to market_data table
CREATE TRIGGER update_market_data_updated_at
    BEFORE UPDATE ON market_data
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- =============================================================================
-- Grant Permissions
-- =============================================================================
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;

-- =============================================================================
-- Initial Data / Health Check
-- =============================================================================
INSERT INTO pipeline_runs (run_id, status, start_time, end_time, rows_processed, features_generated)
VALUES (
    gen_random_uuid(),
    'completed',
    CURRENT_TIMESTAMP - INTERVAL '1 minute',
    CURRENT_TIMESTAMP,
    0,
    0
) ON CONFLICT DO NOTHING;

-- Print success message
DO $$
BEGIN
    RAISE NOTICE 'AlphaRL-Quant database schema initialized successfully!';
    RAISE NOTICE 'Tables created: market_data, model_checkpoints, pipeline_runs, feature_cache, trading_signals';
END $$;
